from enum import Enum

class ResponseSignal(Enum):
    

    FILE_TYPE_NOT_SUPPORTED = "FILE_TYPE_NOT_SUPPORTED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    UPLOAD_SUCCESS = "UPLOAD_SUCCESS"
    UPLOAD_FAILURE = "UPLOAD_FAILURE"
    PROCESSING_FAILED = "PROCESSING_FAILED"
    PROCESSING_SUCCESS = "PROCESSING_SUCCESS"
    NO_FILES_TO_PROCESS = "NO_Files"